### ISSUE TITLE
Issue 1: User can search for pokemon

### ISSUE THREAD

**Issue by marvinloreto** [marvinloreto/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search the Pokémon API with the Pokémon name.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type in the name of a Pokémon in a search box and the picture of the Pokémon and name is loaded.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (190)](https://user-images.githubusercontent.com/117399643/211948112-1623aea7-e811-4218-b4d6-ed33cb06c1d5.png)

![Screenshot (191)](https://user-images.githubusercontent.com/117399643/211948418-7b636027-64cc-4448-a60e-d0f29bf9fdc1.png)
![Screenshot (195)](https://user-images.githubusercontent.com/117399643/212246227-385db168-e3d1-4cc2-99f4-6773dbe53ee5.png)
![Screenshot (192)](https://user-images.githubusercontent.com/117399643/212246233-8778efd9-a018-4cf0-af3c-049f81e9cf79.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML skeleton
- [x] Create header element
- [x] Create proper divs/containers for page content.
- [x] Create html form element, to hold input and search(submit) button. 
- [x] Provide proper CSS styling to match wireframe.
- [x] Listen for 'submit' events on the form element.
- [x] Query select for button/submit element.
- [x] Write handle submit function with parameter that will receive character name from input.
- [x] Within character name function create new instance of XMLHttpRequest and set to xhr variable.
- [x] Write xhr.open method called with two arguments, 'GET' and string for Pokemon API with concatenation of characterName parameter.
- [x] Assign string 'json' to xhr.responseType.
- [x] Check to make sure proper data is being received by console logging the xhr object.
- [x] Add a sibling div element to the div with class row within the main element.
- [x] Add necessary divs to sibling div element for proper column and row setup.
- [x] Add an empty unordered list to sibling div element.
- [x] Define a function for `handleViewSwap`:
  - [x] Changes view to the "results page" when the search button is clicked
  - [x] Changes view from "results page" to home-page when link is clicked
- [x] Define a function that takes the xhr.response object and returns a DOM tree with a list element, an image element, and  paragraph elements.
- [x] Append the DOM tree created to the empty unordered list element in the HTML.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
