### ISSUE TITLE
Issue 3: User can add pokemon to favorites

### ISSUE THREAD

**Issue by marvinloreto** [marvinloreto/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a pokemon to their favorite list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is seeing the details of the pokemon they searched, they can like "add to favorite" to add the pokemon to the favorite list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot (199)](https://user-images.githubusercontent.com/117399643/212450901-882daad6-e49d-4599-a2a6-58baf4ac3cba.png)
![Screenshot (196)](https://user-images.githubusercontent.com/117399643/212450903-bba470ae-f8ec-4fb7-9922-f00037ca1193.png)
![Screenshot (197)](https://user-images.githubusercontent.com/117399643/212450905-844c371f-50b7-41d9-993b-ea04d6ca5a71.png)
![Screenshot (198)](https://user-images.githubusercontent.com/117399643/212450964-4920a19b-dc52-4537-ab85-83a3d8e54eb6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an anchor or button to details page to add to Favorites
- [x] Add div for "Favorites List"
- [x] Add related divs to HTML
- [x] Add event listener click event for favorites list
- [x] Update view swap functionality
- [x] Write a function to generate DOM tree for "Favorites List"
- [x] Update call back function to store data for "Favorites List"
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
