### ISSUE TITLE
Issue 2: User can click the pokemon to see more details 

### ISSUE THREAD

**Issue by marvinloreto** [marvinloreto/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view more details of the searched Pokemon

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (192)](https://user-images.githubusercontent.com/117399643/212245953-12187202-9c34-4ea6-9f65-8de961471e0b.png)
![Screenshot (193)](https://user-images.githubusercontent.com/117399643/212245964-feb679ea-7352-400e-982f-87cf0173f982.png)
![Screenshot (194)](https://user-images.githubusercontent.com/117399643/212246001-a1c045b3-97cf-4f76-993c-268eb561f48b.png)
![Screenshot (195)](https://user-images.githubusercontent.com/117399643/212246025-f468f3b0-d33d-405b-b731-7068d545bb71.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div element with class "container-details" to div element with class "result-container".
- [x] Add proper div element row and column structure for details div.
- [x] Assign all necessary values to pokeData object, using values of xhr object passed through getCharacterLi function.
- [x] Push pokeData object to entries value (empty array) of the data model object.
- [x] Set attribute of DOM created li element to data-character-id = value obtained from xhr object (character.id).
- [x] Add event listener to unordered list element.
- [x] Create callback function to handle click events in the unordered list
- [x] Update viewSwap function to account for new view.
- [x] Ensure all functionality and CSS is proper for both mobile and desktop views.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
